### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by jotarothe** [Anistream/Anistream-Mobile#8]
It worked fine before but now it redirects to some other website.

**Comment by ColaFan69** [comment]
I have the same issue. I wonder what is going on.

**Comment by GoluLiliput** [comment]
Yes now that's some issue... m facing the same bro

**Comment by Riku32** [comment]
FIxed

**Comment by GoluLiliput** [comment]
No the issue is not fixed @Riku32

**Comment by GoluLiliput** [comment]
It still shows external page selection with bunch of list of servers

**Comment by Riku32** [comment]
Did you read the thing that says "We are fixing this problem"

**Comment by Riku32** [comment]
Just wait a few hours

**Comment by GoluLiliput** [comment]
Ok thanks a lot @Riku32

**Comment by CR4KE** [comment]
Still get the " if main servers can't load please change to other server, we are fixing this problem, thank you"

**Comment by Doomslayer-101** [comment]
Same here too

**Comment by GoluLiliput** [comment]
It's not the app problem... It's rgebserver problem. This app's development is stopped and we can't expect any update or fixes on this app by the developper, bcz he s an idiot n doesn't knw anythng lol

**Comment by Riku32** [comment]
It will be fixed if the scrape sources fix their shit, I stopped development because I lost motivation and got a DMCA. Learn english before attempting to insult me :3

**Comment by GoluLiliput** [comment]
So the app will retrn to the original state once the server is fixed? It won't show the page where we see the server selection shit agn?

**Comment by CR4KE** [comment]
I think they're saying, it might not get fixed if they don't fix the server 😔 
Any good alternative apps?

**Comment by GoluLiliput** [comment]
Yes bro... Search for Animestack 2020 on playstore ro google it. U will love the app like hell😍😍😍

**Comment by GoluLiliput** [comment]
> I think they're saying, it might not get fixed if they don't fix the server 😔 
> Any good alternative apps?

Download... Animestack 2020 from playstore or Google. I assure u wl love the app. U can thank me later for it😉

**Comment by CR4KE** [comment]
Cheers will give it a try 😁
